### ISSUE TITLE
Customizing Discovered Items in HA

### ISSUE THREAD

**Issue by wrongisthenewright** [ysard/ebusd_configuration_chaffoteaux_bridgenet#2]
Hi,
you state in the README that with autodiscovery you cannot impose limit on discovered entities, It's not really correct.
I was able to impose limits and steps in Ebusd Mqtt discovred items with the customize option in configuration.yaml in HA

```
customize:
    number.ebusd_energymgr_z1_heat_offset:
      name: Z1 Heat Offset
      min: -7
      max: 7
      step: 1
      mode: box
```

You need obviously to do it for every single input entity but it's a minor problem,since I've noted that a single error in inseting data in HA can result in handling error of the command by ebusd/remote controller/energy manager.

Hope it helps
