### ISSUE TITLE
external temp is wrong

### ISSUE THREAD

**Issue by kenny00111** [ysard/ebusd_configuration_chaffoteaux_bridgenet#5]
Hi, I used your config to my Chaffoteux mira C green boiler, and everything is working fine except the external temp ( as far as I know i don't have an external sensor). 
![image](https://github.com/ysard/ebusd_configuration_chaffoteaux_bridgenet/assets/64666922/74205adb-4f3e-4cc6-b67b-8dfb8469b7b9)
![image](https://github.com/ysard/ebusd_configuration_chaffoteaux_bridgenet/assets/64666922/4edf2a53-cf29-477f-a192-7d937206c55f)

do you know what could be the problem?  i am very new to ebusd

thanks

**Comment by wrongisthenewright** [comment]
Hi,  it probably either the default value sent if the external probe is missing or the decoding is wrong for your model. 
Try searching the raw message that gets intercepted.

You should use ebusctl command to dump the message

**Comment by kenny00111** [comment]
thanks, but exactly how can I do that?

**Comment by wrongisthenewright** [comment]
It depends on how you installed ebusd. Take a look at ebusd documentation but if you have a standard install the command should be

ebusctl grab result all | grep PBSB 

In a docker env.

docker exec -ti EBUDS_CONTAINERNAME ebusctl grab result all | grep PBSB

Where PBSB is the command code of the parameter you're diagnosing.

**Comment by kenny00111** [comment]
I got this reply: 313c2000027647 / 0301ff7f = 18: boiler ext_temp
I guess 0301ff7f need to be decoded?

**Comment by wrongisthenewright** [comment]
You log extract means that the boiler (37 is usually the master address of the boiler in Ariston Group bridgenet) Is asking (that's my interpretation of 2000 PBSB)  to everyone (fe=broadcast) if they have/can provide an up to date value for the 6d26 and 6047 parameters.
In one instance ebusd correctly interpreted the ext temp message in the way that the decoding of the message was successful, ebusd doesn't know that the translation of the 7647 parameter is meaningless/wrong/default.

**Comment by kenny00111** [comment]
Thanks for the great answers I start to understand. It strange that the system knows about the disconnected sensor so my opinion it should default to some value like unknown.

**Comment by wrongisthenewright** [comment]
> Thanks for the great answers I start to understand. It strange that the system knows about the disconnected sensor so my opinion it should default to some value like unknown.

That field is a numeric one. That exclude strings like NULL, VOID etc, you cannot obviously choose 0 as it is a "valid" external temp, my guess is they choose that high number as default and all the Ariston devices recognize this.

BTW have you thought of buying an external probe? It's reasonably cheap (around 20€ here in Italy) and all it needs is a 2 wire cable (the old telephone twisted pair is good enough) from the boiler to function. Having the ext probe you can enable SRA thermoregulation.

If you look in the hardware reverse engineering of this repo you can find also a diy solution (NTC 10k@20°C)

**Comment by kenny00111** [comment]
Do you have a link for the diy solution? I looked it up but couldn't find any ref. I have some sensors lying around

**Comment by kenny00111** [comment]
So it could be possible to emulate the resistance with the esp based on an existing sensor value?

**Comment by wrongisthenewright** [comment]
> So it could be possible to emulate the resistance with the esp based on an existing sensor value?

I don't think so, but you can try, in case of problem disable your "automation" and simply reboot your boiler.
You should continuously update the 7647 parameter with your own value writing it  on the bus. Don't know if the boiler likes it :)

If it was me I 'd go with a physical probe, "original" or custom made but independent from HA , esp, wifi etc.... it's my home in the winter we're speaking of ..

**Comment by kenny00111** [comment]
My idea is rather to use a digital potentiometer to emulate the sensor (not sure yet if it is feasible or not). It would be too much wiring otherwise.

**Comment by ysard** [comment]
Sorry for the delay in replying, it's hard for me to go from project to project
and maintaining them all.

@wrongisthenewright: Thanks for the service :p


So, Yes, you are entirely right in your observations, I had even noted it in my notes.
When the probe is disconnected/absent, the value sent is 32767.

This corresponds to the maximum value of a short before the sign change (0xffff corresponds to -1).
The value is coded on 15bits + 1 sign bit (2^15 = 32767).

There are several solutions:
    
    
- You don't have a temperature sensor, so this sensor is useless to you, banish it from the database 

Ex in your configuration.yaml file   

```yaml
recorder:
  commit_interval: 30
  purge_keep_days: 60
  exclude:
    entities:
      - sensor.ebusd_boiler_ext_temp_0
```      
      
- You can also create a sensor template that uses the sensor value and display a value only if it has meaning.

```yaml
template:
  - sensor:
    - name: Outdoor temperature
      unique_id: outdoor_temperature
      state_class: measurement
      unit_of_measurement: "°C"
      state: >
        {% set ext_temp = states.sensor.ebusd_boiler_ext_temp_0.state | float %}
        
        {% if ext_temp > 100 %}
            #{{ 'unknown' }}
            {{ "Your house is in fire, you should take action for this situation" }}
        {% else %}
            {{ ext_temp | round(1) }}
        {% endif %}

      availability: >
        {% set expected_states = [states.sensor.ebusd_boiler_ext_temp_0]%}
        {{ expected_states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}
```

I haven't tested this code, it's up to you to adapt it but it should work™.


- Personally, I've connected an NTC thermistor to this input, which gives me the temperature of my apartment.
I use the temperature from the homeassistant weather service as the external temperature.

The rest of the calculations involving water law don't change, except that they use these values.

The thermistor is very standard - you'll find it for less than 1€ for 10 of them on aliexpress.
(if you don't fear the wrath of Gaïa or her high priestess Ursula von der Leyen, by ordering something from the other side of the world; Something that's only made there anyway...).

If you have any old laptop batteries to hand, you may be interested to know that these are the thermistors glued to the lithium-ion cells.
You'll find at least 2 in every battery (that's where I got mine from).

This is literally the same component used in official probes.
This gives you an idea of the margin the manufacturer makes on the material (x250 at least).
But you'll get a nice plastic box.


- You can also put a simple 10K resistor on this input to set the value at 20°C...


- The module you're looking to control is called a variable resistor or Digital Rheostat.
Ex component: AD5175 driven by i2c based on a DAC (Digital to Analog Converter).
I've never used such modules.
